spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/dwf2025_1
spring.datasource.username=root
spring.datasource.password=Snoopy123
### server.port = 8085
# carpeta de archivos
app.upload.dir=uploads

springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none